"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from libtbx import load_env

from setuptools import setup

APP = ['Proton8.py']
DATA_FILES = ['Resources', 'Coot.py']
OPTIONS = {'argv_emulation': False,
 'bdist_base': '/Users/vxn01537/P8/build',
 'dist_dir': '/Users/vxn01537/P8/dist',
 'matplotlib_backends': 'wx',
 'semi_standalone': False,
 'includes': ['libtbx.phil.interface', 'libtbx.phil.experimental', 'libtbx.phil.gui_objects',
              'boost_python_meta_ext', 'iotbx_cif_ext', 'iotbx_dtrek_ext', 'iotbx_scalepack_ext', 'iotbx_shelx_ext', 'mmtbx_alignment_ext', 'mmtbx_f_model_ext', 'smtbx_structure_factors_direct_ext',
              ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    
)
